### ISSUE TITLE
Map Layer for returnee map 

### ISSUE THREAD

**Issue by mackh** [PeaceGeeksSociety/SA-UNHCR-Somalia#18]
Somali is requesting map layers with a legend, not clear if records need to be filterable by these zones

[SOM_VolRep_Kenya_Overview_30Sept2016.pdf](https://github.com/PeaceGeeksSociety/SA-UNHCR-Somalia/files/569624/SOM_VolRep_Kenya_Overview_30Sept2016.pdf)

**Comment by PeaceGeeks** [comment]
https://www.ecoi.net/file_upload/1930_1403598415_53a04d044.pdf

**Comment by PeaceGeeksProjects** [comment]
Request Cancelled by eMail (https://mail.google.com/mail/u/0/#label/Projects+Active%2FOther%2FICC-SMS/15844e4f96c496a9):
I just spoke to my protection colleague who was in Dadaab last week, and his directive is that including security information on the map could potentially pose a risk for the refugees. Apologies for the back-and forth on this, but the map will need to only demonstrate services.
 
All best,
 
Claire
